#eureka注册中心对外暴露的端口 提供web界面 查看所有注册的微服务
server:
  port: 8089
#设置注册中心当前主机的主机名  
eureka:
  instance:
    hostname: eurekaserver2
    appname: userservice
  client: 
    registerWithEureka: true
    #是否讲注册中心所有的微服务抓取到本地
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka/
spring: 
    datasource: 
        url: jdbc:mysql://localhost/phonesalemgt
        username: root
        password: sa
        driver-class-name: com.mysql.jdbc.Driver
    application: 
        name: userservice